apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: Slow
  mountOptions:
    - hard
    - nfserver=4.1
  nfs:
    path: /tmp
    server: 172.17.0.2
