apiVersion: v1
kind: Pod
metadata:
  name: cka-02-cpu-loader
  labels:
    name: cpu-loader
spec:
  containers:
  - name: cka-o2-cpu-loader
    image: vish/stress
    resources:
      limits:
        cpu: "1"
      requests:
        cpu: "0.5"
    args:
    - -cpus
    - "1"
