apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod-3
  namespace: xiaomo
spec:
  containers:
    - name: test-container-3
      image: nginx
      volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: special-config
        items:
        - key: SPECIAL_LEVEL
          path: keys
  restartPolicy: Never
