apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod
  namespace: default
spec:
  containers:
    - name: test-container
      image: nginx:1.14.2
      ports:
      - containerPort: 80
      command: ['sh', '-c', 'echo "$(SPECIAL_LEVEL_KEY) $(SPECIAL_TYPE_KEY)" > echo_content.txt']
      env:
        - name: SPECIAL_LEVEL_KEY
          valueFrom:
            configMapKeyRef:
              name: special-config
              key: SPECIAL_LEVEL
        - name: SPECIAL_TYPE_KEY
          valueFrom:
            configMapKeyRef:
              name: special-config
              key: SPECIAL_TYPE
  restartPolicy: Never
