apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-patch
spec:
  template:
    spec:
      containers:
      - name: my-nginx-patch
        resources:
          limits:
            memory: 512Mi
