apiVersion: v1
kind: Pod
metadata:
  name: aws-cli
  labels:
    app: aws-cli
  annotations:
    a: "a"
spec:
  containers:
    - name: aws-cli
      image: amazon/aws-cli
      command:
        - "sleep"
        - "1000000"
  serviceAccountName: g123-i18n-api-sa
  restartPolicy: Never
  terminationGracePeriodSeconds: 1