apiVersion: v1
kind: Pod
metadata:
  name: annotation-second-scheduler
  labels:
    name: muti-scheduler-example
spec:
  schedulerName: my-scheduler
  containers:
    - name: nginx
      image: nginx