apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
    - name: nginx-taint
      image: nginx
  tolerations:
    - key: key1
      value: value1
      operator: Equal
      tolerationSeconds: 3600