apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-env-deployment

spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
      env: test
      release: stable

  template:
    metadata:
      labels:
        app: my-app
        release: stable
        env: test
    spec:
      containers:
        - name: pod-1
          image: nginx
          ports:
            - containerPort: 80
          env:
            - name: TEST_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: my-secret
            - name: TEST_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: my-secret