apiVersion: v1
kind: Pod
metadata:
  labels:
    app: my-app-with-secret
  name: my-secret-test
spec:
  containers:
    - name: my-app-container
      image: nginx
      volumeMounts:
        - mountPath: "/etc/secrets"
          name: secrets #要填卷中的secret的名字(spec.volumes.name)
          readOnly: true
  volumes:
    - name: secrets
      secret:
        secretName: my-secret
