apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo-2
  namespace: xiaomo
spec:
  containers:
  - name: cpu-demo-ctr-2
    image: vish/stress
    resources:
      limits:
        cpu: "1000"
      requests:
        cpu: "1000"
    args:
    - -cpus
    - "2"
