apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume-nfs
  labels:
    type: nfs
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: "192.168.2.100"
    path: "/data/backups"
