apiVersion: v1
kind: ConfigMap
metadata:
  name: special-config
  #  namespace: xiaomo
data:
  special.how: very
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
  #namespace: xiaomo
data:
  log_level: INFO
